const maps = [
  {
    id: 'TV',
    name: 'Tenderness Valley',
    shortName: 'TV',
    order: 1,
    videoSrc: '/assets/maps/TV.mp4',
    slot: { x: 318, y: 260, w: 271, h: 271 },
  },
  {
    id: 'FP',
    name: 'Fel Pit',
    shortName: 'FP',
    order: 2,
    videoSrc: '/assets/maps/FP.mp4',
    slot: { x: 653, y: 260, w: 271, h: 271 },
  },
  {
    id: 'RL',
    name: 'River of Life',
    shortName: 'RL',
    order: 3,
    videoSrc: '/assets/maps/RL.mp4',
    slot: { x: 993, y: 260, w: 271, h: 271 },
  },
  {
    id: 'WH',
    name: 'War Hall',
    shortName: 'WH',
    order: 4,
    videoSrc: '/assets/maps/WH.mp4',
    slot: { x: 1333, y: 260, w: 271, h: 271 },
  },
  {
    id: 'TW',
    name: 'Turbid Waters',
    shortName: 'TW',
    order: 5,
    videoSrc: '/assets/maps/TW.mp4',
    slot: { x: 481, y: 606, w: 271, h: 271 },
  },
  {
    id: 'FA',
    name: 'Fading Autumn',
    shortName: 'FA',
    order: 6,
    videoSrc: '/assets/maps/FA.mp4',
    slot: { x: 824, y: 606, w: 271, h: 271 },
  },
  {
    id: 'MS',
    name: 'Moon Strand',
    shortName: 'MS',
    order: 7,
    videoSrc: '/assets/maps/MS.mp4',
    slot: { x: 1171, y: 606, w: 271, h: 271 },
  },
];

module.exports = { maps };
